export const actionTypes = {

  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  
  GET_ROLES:"GET_ROLES",
  GET_ROLES_SUCCESS:"GET_ROLES_SUCCESS",

  CHANGE_USER_STATUS:"CHANGE_USER_STATUS",

  DELETE_USER:"DELETE_USER",
  OPEN_MODAL:"OPEN_MODAL",
  OPEN_ADD_MODAL:"OPEN_ADD_MODAL",

  CLOSE_MODAL:"CLOSE_MODAL",
  CLOSE_ADD_MODAL:"CLOSE_ADD_MODAL",
  EDITABLE_USER:"EDITABLE_USER",
  
  GET_USER_BY_ID:"GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS:"GET_USER_BY_ID_SUCCESS",
  

 EDIT_USER :"EDIT_USER",
 EDITING_USER:"EDITING_USER"

};
