export const actionTypes = {
  LOGIN: "LOGIN",
  GET_USERS: "GET_USERS",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  GET_USERS_SUCCESS:"GET_USERS_SUCCESS",
  REGISTRATION_SUCCESS:'REGISTRATION_SUCCESS',
  REGISTRATION:'REGISTRATION'
};
