export const actionTypes = {
  TOKEN: "TOKEN",
  LOGOUT: "LOGOUT",
  
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  REGISTRATION: "REGISTRATION",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",

  FORGET_PASSWORD:"FORGET_PASSWORD",
  FORGET_PASSWORD_SUCCESS:"FORGET_PASSWORD_SUCCESS",


};
